"""Constants that are common to all triage tools."""
JIRA_SERVER = "https://issues.redhat.com"
TRIAGE_TICKET_SEARCH_PROJECT = "AITRIAGE"
TRIAGE_TICKET_SEARCH_COMPONENT = "Cloud-Triage"
TRIAGE_TICKET_SEARCH_DEFAULT_DAYS = 31
DATA_DIRECTORY = "/data/triage-tools-tickets"
REPORT_OUTPUT_FILE = "report.json"
JIRA_SEARCH_FAILURE_RETRIES = 10
JIRA_SEARCH_FAILURE_BACKOFF_SECONDS = 2
PARSE_FAILURE_COUNT_FATALITY_THRESHOLD = 10

__all__ = [
    "JIRA_SERVER",
    "TRIAGE_TICKET_SEARCH_PROJECT",
    "TRIAGE_TICKET_SEARCH_COMPONENT",
    "TRIAGE_TICKET_SEARCH_DEFAULT_DAYS",
]
